---
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: svm-latex-anon-ms.tex
header-includes:
   - \usepackage[russian]{babel}
title: "Шаблон диссертации в Markdown и Pandoc"
runhead: "Физика и барабанные палочки"
thanks: "Оригинальный шаблон и файлы для репликации находятся здесь  (http://github.com/svmiller). **Текущая версия**: `r format(Sys.time(), '%B %d, %Y')`; **Связь с автором оригинала**: svmille@clemson.edu; **связь с автором перевода**: aknorre@eu.spb.ru."
author:
- name: Steven V. Miller и Алексей Кнорре
  affiliation: Clemson University и ЕУСПб
abstract: "Когда мне было лет одиннадцать-двенадцать, я устроил у себя дома лабораторию. Она состояла из старого деревянного ящика, в который я приладил полки. У меня был нагреватель, благодаря чему я брал жир и постоянно жарил картошку по-французски. Кроме того, у меня была аккумуляторная батарея и ламповый блок. Чтобы соорудить ламповый блок, я отправился в дешевый хозяйственный магазинчик и купил несколько патронов, которые привинчиваются к деревянному основанию. Потом я соединил их звонковым проводом. Я знал, что, если по-разному комбинировать выключатели - последовательно или параллельно, можно получить разное напряжение. Однако я не знал, что сопротивление ампочки зависит от ее температуры, поэтому результаты моих вычислений разошлись с тем, что я получил на выходе своей цепи. Тем не менее, результат был вполне приемлем. При последовательном соединении лампочки загорались в полсилы и тлеееееееееели, очень здорово, просто классно!"
keywords: "pandoc, r markdown, knitr"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
bibliography: master.bib
biblio-style: apsr
indent: yes
colorlinks: true
---

# Вместо введения

На конференции был один социолог, который написал работу, чтобы ее прочитали все мы, — он написал ее предварительно. Я начал читать эту дьявольщину, и мои глаза просто полезли из орбит: я ни черта не мог в ней понять! Я подумал, что причина в том, что я не прочел ни одной книги из предложенного списка. Меня не отпускало это неприятное ощущение “своей неадекватности” до тех пор, пока я, наконец, не сказал себе: “Я остановлюсь и прочитаю одно предложение медленно, чтобы понять, что, черт возьми, оно значит”.

Итак, я остановился — наугад — и прочитал следующее предложение очень внимательно. Я сейчас не помню его точно, но это было что-то вроде: “Индивидуальный член социального общества часто получает информацию через визуальные, символические каналы”. Я долго с ним мучился, но все-таки перевел. Знаете, что это означает?

“Люди читают” [@Feynman:1949:TP; @Feynman:1949:STA].

# Вы, конечно, шутите, мистер Фейнман!

Некоторые факты моей жизни. Я родился в маленьком городке Фар-Рокуэй недалеко от Нью-Йорка, на берегу моря, в 1918 г. Я жил там до 1935 г. Потом я учился 4 года в Массачусетском технологическом институте (МТИ), а с 1939 г. перешел в Принстон. Работая в Принстоне, я принял участие в Манхэттенском проекте и в апреле 1943 года переехал в Лос-Аламос. С октября или ноября 1946-го до 1951 г. я работал в Корнелле.

В 1941 г. я женился на Арлин, а в 1946 г. во время моего пребывания в Лос-Аламосе она умерла от туберкулеза. Летом 1949-го я посетил Бразилию, а в 1951 году я провел там еще
полгода. Затем я перешел в Калифорнийский технологический институт, где работаю до сих пор.

В конце 1951-го я провел пару недель в Японии. Я поехал туда снова год или два спустя, сразу после того, как вторично женился. Моей второй женой была Мэри Лу. 

Сейчас я женат на Гвинет, она англичанка, и у нас двое детей: Карл и
Мишель. 
Р. Ф. Ф.

## Латинский или итальянский?

В Бруклине была итальянская радиостанция, и мальчишкой я постоянно ееслушал. Я ОБОжал ПЕРЕливчатые ЗВУКи, которые накатывали на меня, словно янежился в океане среди невысоких волн. Я сидел и наслаждался водой, котораянакатывала на меня, этим ПРЕКРАСНЫМ ИТАЛЬЯНСКИМ языком. В итальянских передачах всегда разыгрывалась какая-нибудь житейская ситуация и разгоралисьжаркие споры между женой и мужем. Высокий голос: "Нио теко ТИЕто капето ТУтто... "Громкий, низкий голос: "ДРО тоне пала ТУтто!!" (со звуком пощечины).

Это было классно! Я научился изображать все эти эмоции: я мог плакать;я мог смеяться и все такое прочее. Итальянский язык прекрасен.В Нью-Йорке рядом с нами жили несколько итальянцев. Иногда, когда якатался на велосипеде, какой-нибудь водитель-итальянец огорчался из-за меня,высовывался из своего грузовика и, жестикулируя, орал что-то вроде: "МеаРРУча ЛАМпе этта ТИче!". Я чувствовал себя полным дерьмом. Что он сказал мне? Что я долженкрикнуть в ответ? Тогда я спросил своего школьного друга-итальянца, и он сказал: "Просто скажи: "А те! А те!", что означает: "И тебе того же! И тебе того же!"". Я подумал, что это просто великолепная мысль. И я обычно говорил: "А те! А те!" и, конечно, жестикулировал. Затем, обретя уверенность, я продолжил развивать свои способности. Когда я ехал на  велосипеде и какая-нибудь дама, которая ехала на машине, оказывалась у меня на пути, я говорил: "ПУцциа а ла маЛОче!", - она тут же сжималась! Какой-то негодный итальянский мальчишка грязно обругал ее!

Было не так то просто определить, что этот язык не был подлинным итальянским языком. Однажды, когда я был в Принстоне и заехал на велосипеде на стоянку Палмеровской лаборатории, кто-то загородил мне дорогу. Мои привычки ничуть не изменились: жестикулируя и хлопая тыльной стороной одной руки о другую, я крикнул: "оРЕцце каБОНка МИче!". А наверху, по другую сторону длинного газона, садовник-итальянец сажает какие-то растения. Он останавливается, машет рукой и радостно кричит: "РЕццама Лла!" Я отзываюсь: "РОНте БАЛта!", тоже приветствуя его. Он не знал, что я не знаю (а я действительно не знал), что он сказал; а он не знал, что сказал я. Но все было в порядке! Все вышло здорово! Это работает! Кроме того, когда итальянцы слышат мою интонацию, они признают во мне итальянца - может быть, он говорит не на римском наречии, а на миланском, какая, к черту, разница. Важно, что он иТАЛЬянец! Так что это просто классно!

Но вы должны быть абсолютно уверены в себе. Продолжайте ехать, и ничего с вами не случится. Однажды я приехал домой из колледжа на каникулы и застал сестру очень расстроенной, почти плачущей: ее герлскаутская организация устраивала банкет для девочек и их пап, но нашего отца не было дома: он где-то продавал униформы. Я сказал, что несмотря на то, что я ее брат, я пойду с ней (я на девять лет старше ее, поэтому затея была не такая уж безумная). Когда мы приехали на место, я немного посидел с отцами, но скоро онимне до смерти надоели. Все отцы привезли своих дочек на этот милый маленькийбанкет, а сами говорили только о фондовой бирже: они не знали, о чем разговаривать со своими собственными детьми, не говоря уже о друзьях своих детей.

Во время банкета девочки развлекали нас небольшими пародиями, чтением стихотворений и т.п. Потом внезапно они принесли какую-то забавную штуку,похожую на фартук, с дыркой наверху, куда нужно было просовывать голову. Девочки объявили, что теперь папы будут развлекать их. Итак, каждый отец встает, просовывает голову в фартук и что-нибудь говорит - один мужик рассказал "У Мэри был ягненок" - в общем, они не знают,что делать. Я тоже не знал, что делать, но когда подошла моя очередь выступать, я сказал, что расскажу им небольшое стихотворение и что я извиняюсь, что оно не на английском языке, но я все равно уверен, что ониего оценят.А ТУЦЦО ЛАНТО- Поиси ди Паре. ТАНто САка ТУЛна ТИ, на ПУта ТУча ПУти ТИла. РУНто КАта ЧАНто ЧАНта МАНто ЧИла ТИда. ЙАЛЬта КАра СУЛЬда МИла ЧАта ПИча ПИно ТИто БРАЛЬда пе теЧИна нана ЧУНда дала ЧИНда лапа ЧУНда! РОНто пити КА ле, а ТАНто ЧИНтоквинта ЛАЛЬда О ля ТИНта далла ЛАЛЬта, ЙЕНта ПУча лалла ТАЛЬта!

Я прочел три или четыре строфы, проявив все эмоции, которые слышал по итальянскому радио, а дети понимали все, катаясь от хохота в проходе между рядами. После окончания банкета ко мне подошли руководитель скаутского отряда ишкольная учительница. Они сказали мне, что обсуждали мое стихотворение. Одна из них считала, что это итальянский язык, а другая - что это латинский. Учительница спросила: "Так кто же из нас прав?" Я сказал: "Спросите у своих воспитанниц - они сразу поняли, какой это язык".


\newpage

<!--
# References
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}
\vspace*{-0.2in}
\noindent
-->
